# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
#   schedule:
#     - cron: '0 * * * *'

#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        snyk_install_method: [npm, binary]
        node_version: [12]
        include:
          # includes a new variable of npm with a value of 2
          # for the matrix leg matching the os and version
          - snyk_install_method: npm
            node_version: 8
          - snyk_install_method: npm
            node_version: 10

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install node
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    
    - name: Install Snyk with npm
      if: ${{ matrix.snyk_install_method == 'npm' }}
      run: |
        node -v
        echo "install snyk with npm"
        npm install -g snyk

    - name: Install Snyk with binary
      if: ${{ matrix.snyk_install_method == 'binary' }}
      run: |
        echo "install snyk with binary"

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

