# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
#   schedule:
#     - cron: '0 * * * *'

#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        snyk_install_method: [binary] # npm, binary
        node_version: [8, 10, 12]
        exclude:
          - snyk_install_method: binary
            node_version: 8
          - snyk_install_method: binary
            node_version: 10

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    
    - name: Install Snyk with npm
      if: ${{ matrix.snyk_install_method == 'npm' }}
      run: |
        echo "node_version: ${{ matrix.node_version }}"
        node -v
        echo "install snyk with npm"
        npm install -g snyk

    - name: Install Snyk with binary - non-Windows
      if: ${{ matrix.snyk_install_method == 'binary' && matrix.os != 'windows-latest' }}
      run: |
        echo "install snyk with binary"
        latest_version=$(curl -Is "https://github.com/snyk/snyk/releases/latest" | grep "Location" | sed s#.*tag/##g | tr -d "\r")
        snyk_cli_dl_linux="https://github.com/snyk/snyk/releases/download/${latest_version}/snyk-linux"
        curl -Lo ./snyk $snyk_cli_dl_linux
        chmod -R +x ./snyk
        sudo mv ./snyk /usr/local/bin/snyk
        which snyk

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
